name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/react-node-cicd:latest .
    - name: Push to DockerHub
      run: docker push "${{ secrets.DOCKER_USERNAME }}"/react-node-cicd:latest
    - name: TestDocker ImageLocally
      run: docker run -it anindyobose/react-node-cicd:latest

